# Notebook de Estrutura de Dados e Algoritmos de Ordenação

Centro de Ensino Unificado de Brasília - UniCeub

Professor: Pedro Henrique Rodrigues Mendes

2° Semestre de 2023

**Curso:** Estrutura de Dados

**Aluno:** Wellerson Pereira do Couto

## Introdução

Área onde o aluno deverá detalhar e introdudizr o leitor ao problema: [Compatilhamento de Bicicletas em Brasília](https://www.kaggle.com/datasets/joseguilhermelopes/bike-sharing-system-in-brasilia-brazil).

A presente avaliação procura resolver o problema de compartilhamento de bicicletas em Brasília.

## Importação dos Dados

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/bike-sharing-system-in-brasilia-brazil/df_stations.csv
/kaggle/input/bike-sharing-system-in-brasilia-brazil/df_rides.csv

In [2]:
df_rides = pd.read_csv('../input/bike-sharing-system-in-brasilia-brazil/df_rides.csv', sep=',')
df_stations = pd.read_csv('../input/bike-sharing-system-in-brasilia-brazil/df_stations.csv', sep=',')

## Formatação dos Dados

In [3]:
# transformando a coluna user_birthdate no tipo data
df_rides['user_birthdate'] = df_rides['user_birthdate'].astype("datetime64")

## Listas e Filas

O Aluno deverá implementar um sistema de **Fila (first-in first-out) e Pilha (last in, first out)** com base na classe "rides" abaixo. 

O objetivo é criar um "buffer de requisições" utilizando a Classe Ride, portanto, quando um usuário quando solicita um serviço de bicicleta, a requisição dele deve organizada em uma Fila (*first-in first-out*) ou Pilha (*last in, first out*) de N tamanho para ser processada no sistema de forma organizada.

**A classe Ride pode ser alterada para adequação ao sistemas de fila e pilha, portanto, sempre detalhando as mudanças no código.**

**Aluno deverá instanciar as classes de FILA ou PILHA evidenciando o funcionamento da estrutura de dados**

**Comentar o código e detalhando o embasamento teórico para implementação da técnica.**

In [4]:
class ride:
    
    uf_array = ['AP', 'DF', 'SP', 'RS', 'PR', 'RJ', 'GO', 
                'AC', 'MA', 'PA', 'MG', 'RN', 'PE', 'MT', 
                'ES', 'PB', 'RR', 'BA', 'AL', 'PI', 'CE', 
                'SC', 'RO', 'AM', 'MS', 'TO', 'SE'] 
    
    gender_array = ['M','F']
    
    def __init__(self, gender, birthdate, residence, station_start, proximo = None):
        
        self.db = df_rides
        self.db_stations = df_stations
        self.proximo = proximo
        
        status = True
        
        if gender in ride.gender_array:
            pass
        else:
            status = False
            print("Não Possui essa informação de genero na base da dados")
            
        if  station_start in self.db_stations.station.unique():
            pass
        else:
            print("Não Possui essa informação de estação na base da dados")
            status = False    
            
        if  residence in ride.uf_array:
            pass
        else:
            print("Não Possui essa informação de UF brasileiro na base da dados")
            status = False 
        
        if status:
            self.status = "Iniciado"
            self.gender = gender
            self.birthdate = birthdate
            self.residence = residence
            self.ride_date =  pd.Timestamp.now().strftime('%Y-%m-%d')
            self.time_start = pd.Timestamp.now().strftime('%H:%M:%S')
            self.station_start = station_start
            
            
            self.index = len(self.db.index)
            
            self.time_end = None
            self.station_end = None
            self.ride_duration = None
            self.ride_late = None
            
            insert_list = [self.gender,
                          self.birthdate,
                          self.residence,
                          self.ride_date,
                          self.time_start,
                          self.time_end,
                          self.station_start,
                          self.station_end,
                          self.ride_duration,
                          self.ride_late]
            
            print(insert_list)
            self.db.loc[self.index] = insert_list
            
        else:
            print('Erro de Validação ou insert na base')
                
    
    def user_age(self):
        print(int(str((pd.Timestamp.now() - pd.to_datetime(self.birthdate, format='%Y-%m-%d') ) /365)[:2].strip()))
        
    def get(self):
        
        get_list = [self.gender,
                    self.birthdate,
                    self.residence,
                    self.ride_date,
                    self.time_start,
                    self.time_end,
                    self.station_start,
                    self.station_end,
                    self.ride_duration,
                    self.ride_late]
        
        print(get_list)
        
    def finish_ride(self, station_end):
        
        status =  True
        
        if  station_end in self.db_stations.station.unique():
            pass
        else:
            print("Não Possui essa informação como padrão na base da dados")
            status = False
        
        if status:
            
            self.status = "Concluido"
            self.time_end = pd.Timestamp.now().strftime('%H:%M:%S')
            self.station_end =  station_end
            self.ride_duration = pd.Timedelta(pd.Timestamp.now() - pd.to_datetime(self.ride_date + ' ' + self.time_end)) / pd.Timedelta('60s')
            
            if self.ride_duration >= 60:
                self.ride_late =   1
            else:
                self.ride_late =   0
            
            insert_list = [self.gender,
                          self.birthdate,
                          self.residence,
                          self.ride_date,
                          self.time_start,
                          self.time_end,
                          self.station_start,
                          self.station_end,
                          "{0:0.2f}".format(self.ride_duration),
                          self.ride_late]
            
            print(insert_list)
            self.db.loc[self.index] = insert_list
            
        else:
            print('Erro de Validação ou insert na base')

In [5]:
import random
from pprint import pprint
from re import L
import time
from ctypes import pointer

In [6]:
class fila:
    def __init__(self,data = None, prox = None):
        self.data = data    
        self.prox = prox
        
class pilha:
    def __init__(self,data = None, ant = None):
        self.data = data    
        self.ant = ant

### Fila (first-in first-out)

In [7]:
class line_list: #Inicia a fila
    def __init__(self):
        self.head = None
        self.shape = 0
    
    def getno(self, ind): #Pega um nó através do indice 
        pointer = self.head
        for i in range(ind):
            if pointer:
                pointer = pointer.prox
            else:
                raise IndexError("Index fora do escopo")
        return pointer
        
    
    def line_add(self, x): #Adiciona um item seguinta a fila
        if self.head:
            pointer = self.head
            while(pointer.prox):
                pointer = pointer.prox
            pointer.prox = fila(x)
        else:
            self.head = fila(x)
        self.shape += 1
        
    def line_drop(self): # Remove o primeiro item da fila, sendo o primeiro a entrar e o primeiro a sair
            self.head = self.head.prox
            self.shape -= 1
        
    def __len__(self): #Depois de remover o primeiro, verifica o tamanho da fila 
        return self.shape   

list = line_list()#Instancia da class

def create_line_ride(): #Usa a class ride na fila
    created_ride = ride(random.choice(ride.gender_array),
        str(df_rides.user_birthdate[random.randint(0,287321)])[0:10],
        random.choice(ride.uf_array),
        str(df_rides.station_start[random.randint(0,287320)]).strip()
        )
    list.line_add(created_ride)
    
for x in range(6):
    create_line_ride()    

def finish_ride_line(): #Termina um passeio (ride) na fila
    list.getno(0).data.finish_ride(df_stations.station[random.randint(0,48)])
    list.line_drop()
    
for x in range(list.shape):    
    finish_ride_line()
    time.sleep(1)

['M', '1992-07-13', 'RS', '2023-09-29', '00:49:42', None, '14 - Brasília Shopping', None, None, None]
['M', '1979-09-22', 'PE', '2023-09-29', '00:49:44', None, '38 - SQN 205', None, None, None]
['F', '1998-12-15', 'RS', '2023-09-29', '00:49:44', None, '15 - Brasil 21', None, None, None]
['F', '1994-09-06', 'PE', '2023-09-29', '00:49:44', None, '11 - Rodoviária 2', None, None, None]
['F', '1974-09-08', 'AM', '2023-09-29', '00:49:45', None, '12 - Rodoviária 3', None, None, None]
['M', '1996-04-12', 'PA', '2023-09-29', '00:49:45', None, '5 - Setor Hoteleiro Norte', None, None, None]
['M', '1992-07-13', 'RS', '2023-09-29', '00:49:42', '00:49:45', '14 - Brasília Shopping', '33 - EQS 104/304', '0.00', 0]
['M', '1979-09-22', 'PE', '2023-09-29', '00:49:44', '00:49:46', '38 - SQN 205', '15 - Brasil 21', '0.00', 0]
['F', '1998-12-15', 'RS', '2023-09-29', '00:49:44', '00:49:47', '15 - Brasil 21', '31 - EQS 204/205', '0.00', 0]
['F', '1994-09-06', 'PE', '2023-09-29', '00:49:44', '00:49:48', '11 - Rodoviária 2', '47 - EQN 410/411', '0.01', 0]
['F', '1974-09-08', 'AM', '2023-09-29', '00:49:45', '00:49:49', '12 - Rodoviária 3', '5 - Setor Hoteleiro Norte', '0.01', 0]
['M', '1996-04-12', 'PA', '2023-09-29', '00:49:45', '00:49:50', '5 - Setor Hoteleiro Norte', '500 - Deck Sul Kids', '0.01', 0]

### Pilha (last in, first out)

In [8]:
class pile_list: #Inicia a fila com topo vazio
    def __init__(self):
        self.top = None
        self.shape = 0
 
    def getno(self, ind):
        pointer = self.top
        # Percorre a pilha até o índice desejado (índice negativo representa contar de trás para frente)
        for i in range(ind):
            if pointer:
                pointer = pointer.ant
            else:
                raise IndexError("Index fora de alcance")
        
        return pointer
        
    def pile_add(self, elemento): #Adiciona itens a pilha
        pointer = pilha(elemento)
        pointer.ant = self.top
        self.top = pointer
        self.shape += 1         
        
    def pile_drop(self): # Remove itens do topo da pilha
        self.top = self.top.ant
        self.shape -= 1
        
    def __len__(self):
        return self.shape   


    
pile = pile_list()
    
def create_pile_ride(): #Usa class ride na pilha
    created_ride = ride(random.choice(ride.gender_array),
        str(df_rides.user_birthdate[random.randint(0,287321)])[0:10],
        random.choice(ride.uf_array),
        str(df_rides.station_start[random.randint(0,287320)]).strip()
        )
    pile.pile_add(created_ride)
    
for x in range(6):
    create_pile_ride()    

print("---------")

def finish_pile_ride(): #Termina o passeio na pilha
    pile.getno(-1).data.finish_ride(df_stations.station[random.randint(0,48)])
    pile.pile_drop()

for x in range(pile.shape):
    finish_pile_ride()

['M', '1994-08-10', 'CE', '2023-09-29', '00:49:51', None, '15 - Brasil 21', None, None, None]
['M', '1985-04-02', 'RJ', '2023-09-29', '00:49:51', None, '8 - Ministério da Defesa', None, None, None]
['M', '2000-04-05', 'MG', '2023-09-29', '00:49:51', None, '16 - SRTVS', None, None, None]
['F', '1997-04-08', 'RN', '2023-09-29', '00:49:51', None, '15 - Brasil 21', None, None, None]
['F', '1999-09-08', 'MT', '2023-09-29', '00:49:51', None, '4 - Torre de TV', None, None, None]
['F', '1994-03-19', 'MA', '2023-09-29', '00:49:51', None, '6 - Rodoviária', None, None, None]
---------
['F', '1994-03-19', 'MA', '2023-09-29', '00:49:51', '00:49:51', '6 - Rodoviária', '30 - TSE', '0.02', 0]
['F', '1999-09-08', 'MT', '2023-09-29', '00:49:51', '00:49:52', '4 - Torre de TV', '28 - CNMP - Conselho Nacional do Ministério Público', '0.00', 0]
['F', '1997-04-08', 'RN', '2023-09-29', '00:49:51', '00:49:52', '15 - Brasil 21', '45 - Centro Olímpico', '0.00', 0]
['M', '2000-04-05', 'MG', '2023-09-29', '00:49:51', '00:49:52', '16 - SRTVS', '37 - EQN 104/105', '0.00', 0]
['M', '1985-04-02', 'RJ', '2023-09-29', '00:49:51', '00:49:52', '8 - Ministério da Defesa', '22 - 102 Sul', '0.00', 0]
['M', '1994-08-10', 'CE', '2023-09-29', '00:49:51', '00:49:52', '15 - Brasil 21', '17 - Shopping Pátio Brasil', '0.00', 0]

## Algortimos de Ordenação
O Aluno desenvolve os algoritmos de ordenação abaixo, com o objetivo de ordenar o dataset **df_rides** embaralhado, utilizar o **df_rides.index** para ordenação.

**Realizar a Ánalise de Complexidade em cada algoritmos abordados (Notação Big O e Melhor Caso/Pior Caso)**

**Ao executar as células de código com os algoritmos de ordenação, utilizar o %%time para estimar o tempo de processamento**

**Sempre comentar o código e documentar o embasamento teórico para implementação da técnica de ordenação.**

In [9]:
df_rides.head(5)

,user_gender,user_birthdate,user_residence,ride_date,time_start,time_end,station_start,station_end,ride_duration,ride_late
0,M,1971-06-08 00:00:00,NaN,2018-01-01,06:05:18,06:21:33,11 - Rodoviária 2,41 - Instituto de Artes,16.25,0.0
1,M,1989-02-11 00:00:00,DF,2018-01-01,06:27:01,06:32:17,26 - Ministério da Saude,28 - CNMP - Conselho Nacional do Ministério Pú...,5.266667,0.0
2,M,1968-07-19 00:00:00,NaN,2018-01-01,06:29:33,06:44:57,11 - Rodoviária 2,43 - Biblioteca Central,15.4,0.0
3,M,1991-12-19 00:00:00,NaN,2018-01-01,06:53:53,06:59:45,10 - Ministério dos Transportes,6 - Rodoviária,5.866667,0.0
4,M,1969-03-03 00:00:00,DF,2018-01-01,06:58:56,17:40:04,15 - Brasil 21,11 - Rodoviária 2,641.133333,1.0

In [10]:
 df_rides = df_rides.sample(frac=1,random_state=42)

In [11]:
# printando os 5 primeiros registros da tabela df_stations
df_rides.head(5)

,user_gender,user_birthdate,user_residence,ride_date,time_start,time_end,station_start,station_end,ride_duration,ride_late
166743,F,1979-06-16 00:00:00,DF,2018-06-09,06:55:33,NaN,37 - EQN 104/105,11 - Rodoviária 2,NaN,NaN
107841,F,1954-02-09 00:00:00,DF,2018-04-29,23:29:19,23:37:11,11 - Rodoviária 2,23 - STF,7.866667,0.0
172128,M,1984-11-06 00:00:00,NaN,2018-06-12,17:50:59,NaN,46 - EQN 408/409,32 - SQS 305,NaN,NaN
187892,M,1981-09-05 00:00:00,NaN,2018-06-24,16:47:50,NaN,15 - Brasil 21,15 - Brasil 21,NaN,NaN
156346,M,1982-09-26 00:00:00,NaN,2018-06-02,20:30:46,NaN,16 - SRTVS,34 - Shopping Mall,NaN,NaN

### Bubblesort

O Bubblesort é um dos algoritmos de ordenação mais simples, mas também um dos menos eficientes.
Funciona comparando repetidamente pares de elementos adjacentes e trocando-os se estiverem na ordem errada.
Continua esse processo até que nenhuma troca seja necessária, o que indica que a lista está ordenada.
Sua complexidade de tempo no pior caso é O(n^2), onde n é o número de elementos na lista, tornando-o ineficiente para grandes conjuntos de dados.

In [12]:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        swapped = False
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]  # Troca elementos
                swapped = True
        if not swapped:
            break
    return arr

In [13]:
df_rides = pd.read_csv('../input/bike-sharing-system-in-brasilia-brazil/df_rides.csv', sep=',')

In [14]:
df_rides.head(100)

,user_gender,user_birthdate,user_residence,ride_date,time_start,time_end,station_start,station_end,ride_duration,ride_late
0,M,1971-06-08,NaN,2018-01-01,06:05:18,06:21:33,11 - Rodoviária 2,41 - Instituto de Artes,16.250000,0.0
1,M,1989-02-11,DF,2018-01-01,06:27:01,06:32:17,26 - Ministério da Saude,28 - CNMP - Conselho Nacional do Ministério Pú...,5.266667,0.0
2,M,1968-07-19,NaN,2018-01-01,06:29:33,06:44:57,11 - Rodoviária 2,43 - Biblioteca Central,15.400000,0.0
3,M,1991-12-19,NaN,2018-01-01,06:53:53,06:59:45,10 - Ministério dos Transportes,6 - Rodoviária,5.866667,0.0
4,M,1969-03-03,DF,2018-01-01,06:58:56,17:40:04,15 - Brasil 21,11 - Rodoviária 2,641.133333,1.0
...,...,...,...,...,...,...,...,...,...,...
95,F,1969-01-29,DF,2018-01-01,13:33:30,14:11:24,38 - SQN 205,15 - Brasil 21,37.900000,0.0
96,F,1971-07-17,DF,2018-01-01,13:34:13,15:41:44,31 - EQS 204/205,31 - EQS 204/205,127.516667,1.0
97,M,1976-09-04,NaN,2018-01-01,13:37:42,15:34:30,15 - Brasil 21,15 - Brasil 21,116.800000,1.0
98,M,1974-06-26,PR,2018-01-01,13:40:13,14:20:15,35 - CLN 403,35 - CLN 403,40.033333,0.0
99,F,1981-03-19,DF,2018-01-01,13:41:24,14:20:50,35 - CLN 403,35 - CLN 403,39.433333,0.0

**Melhor caso O(n):**

In [15]:
%%time


#Cópia dos 100 primeiros elementos do df_rides 
dfr = df_rides.head(100).copy()


#Cópia dos índices dos 100 primeiros elementos do df_rides
arr = df_rides.head(100).index.values.copy()

bubble_sort(arr)

CPU times: user 381 µs, sys: 35 µs, total: 416 µs
Wall time: 396 µs

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

**Pior caso O(n²)**

In [16]:
df_rides = df_rides.sample(frac=1,random_state=42)

In [17]:
df_rides.head(100)

,user_gender,user_birthdate,user_residence,ride_date,time_start,time_end,station_start,station_end,ride_duration,ride_late
145752,M,1950-08-25,DF,2018-05-27,18:01:12,18:12:16,4 - Torre de TV,12 - Rodoviária 3,11.066667,0.0
125244,M,1995-10-30,NaN,2018-05-13,14:58:13,16:58:33,15 - Brasil 21,15 - Brasil 21,120.333333,1.0
89296,NaN,1990-06-08,SP,2018-04-14,19:21:25,19:51:08,10 - Ministério dos Transportes,39 - CLN 406,29.716667,0.0
251533,F,1984-09-20,NaN,2018-08-08,17:16:55,17:21:19,22 - 102 Sul,21 - EQS 202 / 203,4.400000,0.0
278236,M,1963-03-02,DF,2018-08-26,13:32:56,14:15:20,25 - Deck Sul,25 - Deck Sul,42.400000,0.0
...,...,...,...,...,...,...,...,...,...,...
103237,F,1995-07-25,DF,2018-04-26,07:24:57,08:00:13,45 - Centro Olímpico,45 - Centro Olímpico,35.266667,0.0
118011,F,1992-03-18,NaN,2018-05-07,18:21:34,18:51:20,3 - Centro de Convenções,41 - Instituto de Artes,29.766667,0.0
35793,M,1996-12-17,DF,2018-02-17,06:50:26,06:54:38,6 - Rodoviária,8 - Ministério da Defesa,4.200000,0.0
130178,M,1995-10-17,NaN,2018-05-16,20:13:37,20:32:17,42 - PAT,38 - SQN 205,18.666667,0.0
134129,M,2004-09-07,NaN,2018-05-20,12:12:50,13:22:30,5 - Setor Hoteleiro Norte,5 - Setor Hoteleiro Norte,69.666667,1.0

In [18]:
%%time


#Cópia dos 100 primeiros elementos do df_rides 
dfr = df_rides.head(100).copy()


#Cópia dos índices dos 100 primeiros elementos do df_rides
arr = df_rides.head(100).index.values.copy()

bubble_sort(arr)

CPU times: user 5.24 ms, sys: 21 µs, total: 5.26 ms
Wall time: 5.24 ms

array([  1105,   2321,   5630,  12044,  16268,  18408,  18838,  19697,
        22786,  24669,  25857,  27021,  32936,  35793,  39945,  44836,
        46142,  51341,  51608,  53236,  54783,  63620,  76475,  76645,
        80641,  89296,  89665,  90036,  90796,  97152, 103237, 114238,
       118011, 119213, 120658, 125244, 127818, 129773, 130178, 131396,
       131452, 131535, 134129, 135971, 139104, 139321, 140265, 144389,
       144416, 145671, 145752, 147930, 151866, 163204, 165459, 165520,
       165548, 168238, 176174, 176567, 183711, 184639, 185411, 185793,
       187392, 192404, 192446, 194572, 201511, 203610, 206419, 214492,
       214826, 216357, 217499, 217828, 218408, 223783, 225094, 225120,
       226932, 227417, 228923, 234420, 242288, 245820, 246884, 247830,
       251533, 252731, 256552, 264020, 268057, 269642, 271166, 273516,
       277128, 278236, 282300, 286966])

### Mergesort

O Mergesort é um algoritmo de ordenação dividir para conquistar que é conhecido por sua eficiência e estabilidade.
Divide a lista em sublistas menores, ordena essas sublistas e, em seguida, combina-as para obter a lista ordenada final.
Possui uma complexidade de tempo média e no pior caso de O(n log n), tornando-o eficiente para grandes conjuntos de dados.
É um algoritmo estável, o que significa que a ordem relativa de elementos iguais é preservada.

In [19]:
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        left_half = arr[:mid]
        right_half = arr[mid:]

        merge_sort(left_half)
        merge_sort(right_half)

        i = j = k = 0

        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                arr[k] = left_half[i]
                i += 1
            else:
                arr[k] = right_half[j]
                j += 1
            k += 1

        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1

        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1

    return arr

In [20]:
df_rides = pd.read_csv('../input/bike-sharing-system-in-brasilia-brazil/df_rides.csv', sep=',')

In [21]:
df_rides.head(100)

,user_gender,user_birthdate,user_residence,ride_date,time_start,time_end,station_start,station_end,ride_duration,ride_late
0,M,1971-06-08,NaN,2018-01-01,06:05:18,06:21:33,11 - Rodoviária 2,41 - Instituto de Artes,16.250000,0.0
1,M,1989-02-11,DF,2018-01-01,06:27:01,06:32:17,26 - Ministério da Saude,28 - CNMP - Conselho Nacional do Ministério Pú...,5.266667,0.0
2,M,1968-07-19,NaN,2018-01-01,06:29:33,06:44:57,11 - Rodoviária 2,43 - Biblioteca Central,15.400000,0.0
3,M,1991-12-19,NaN,2018-01-01,06:53:53,06:59:45,10 - Ministério dos Transportes,6 - Rodoviária,5.866667,0.0
4,M,1969-03-03,DF,2018-01-01,06:58:56,17:40:04,15 - Brasil 21,11 - Rodoviária 2,641.133333,1.0
...,...,...,...,...,...,...,...,...,...,...
95,F,1969-01-29,DF,2018-01-01,13:33:30,14:11:24,38 - SQN 205,15 - Brasil 21,37.900000,0.0
96,F,1971-07-17,DF,2018-01-01,13:34:13,15:41:44,31 - EQS 204/205,31 - EQS 204/205,127.516667,1.0
97,M,1976-09-04,NaN,2018-01-01,13:37:42,15:34:30,15 - Brasil 21,15 - Brasil 21,116.800000,1.0
98,M,1974-06-26,PR,2018-01-01,13:40:13,14:20:15,35 - CLN 403,35 - CLN 403,40.033333,0.0
99,F,1981-03-19,DF,2018-01-01,13:41:24,14:20:50,35 - CLN 403,35 - CLN 403,39.433333,0.0

**Melhor Caso e Pior nLog2(n):**

In [22]:
%%time


#Cópia dos 100 primeiros elementos do df_rides 
dfr = df_rides.head(100).copy()


#Cópia dos índices dos 100 primeiros elementos do df_rides
arr = df_rides.head(100).index.values.copy()

merge_sort(arr)

CPU times: user 1.26 ms, sys: 23 µs, total: 1.28 ms
Wall time: 1.26 ms

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

**Pior Caso:**

Array desordenado

In [23]:
df_rides = df_rides.sample(frac=1,random_state=42)

In [24]:
df_rides.head(100)

,user_gender,user_birthdate,user_residence,ride_date,time_start,time_end,station_start,station_end,ride_duration,ride_late
145752,M,1950-08-25,DF,2018-05-27,18:01:12,18:12:16,4 - Torre de TV,12 - Rodoviária 3,11.066667,0.0
125244,M,1995-10-30,NaN,2018-05-13,14:58:13,16:58:33,15 - Brasil 21,15 - Brasil 21,120.333333,1.0
89296,NaN,1990-06-08,SP,2018-04-14,19:21:25,19:51:08,10 - Ministério dos Transportes,39 - CLN 406,29.716667,0.0
251533,F,1984-09-20,NaN,2018-08-08,17:16:55,17:21:19,22 - 102 Sul,21 - EQS 202 / 203,4.400000,0.0
278236,M,1963-03-02,DF,2018-08-26,13:32:56,14:15:20,25 - Deck Sul,25 - Deck Sul,42.400000,0.0
...,...,...,...,...,...,...,...,...,...,...
103237,F,1995-07-25,DF,2018-04-26,07:24:57,08:00:13,45 - Centro Olímpico,45 - Centro Olímpico,35.266667,0.0
118011,F,1992-03-18,NaN,2018-05-07,18:21:34,18:51:20,3 - Centro de Convenções,41 - Instituto de Artes,29.766667,0.0
35793,M,1996-12-17,DF,2018-02-17,06:50:26,06:54:38,6 - Rodoviária,8 - Ministério da Defesa,4.200000,0.0
130178,M,1995-10-17,NaN,2018-05-16,20:13:37,20:32:17,42 - PAT,38 - SQN 205,18.666667,0.0
134129,M,2004-09-07,NaN,2018-05-20,12:12:50,13:22:30,5 - Setor Hoteleiro Norte,5 - Setor Hoteleiro Norte,69.666667,1.0

In [25]:
%%time


#Cópia dos 100 primeiros elementos do df_rides 
dfr = df_rides.head(100).copy()


#Cópia dos índices dos 100 primeiros elementos do df_rides
arr = df_rides.head(100).index.values.copy()

merge_sort(arr)

CPU times: user 1.36 ms, sys: 0 ns, total: 1.36 ms
Wall time: 1.35 ms

array([  1105,   1105,   1105,   1105,   1105,   1105,   1105,   1105,
         1105,   1105,   1105,   1105,   1105,   1105,   1105,   1105,
         1105,   1105,   1105,   1105,   1105,   1105,   1105,   1105,
         1105,   1105,   1105,   1105,   1105,   1105,   1105,   1105,
         1105,   1105,   1105,   1105,   1105,   1105,   1105,   1105,
         1105,   1105,   1105,   1105,   1105,   1105,   1105,   1105,
         1105,   1105,   1105,   1105,   1105,   1105,   1105,   1105,
         1105,   1105,   2321,   2321,   2321,   2321,   2321,   2321,
         2321,   2321,   2321,   2321,   2321,   2321,   2321,   2321,
         2321,   2321,   2321,   2321,   2321,   2321,   2321,   2321,
         2321,   2321,   2321,   2321,   2321,   2321,   2321,   2321,
         2321,   2321,   2321,   2321,   2321,   2321,  35793,  35793,
        35793,  35793, 130178, 134129])

### Heapsort

O Heapsort é um algoritmo de ordenação baseado em uma estrutura de dados chamada heap binário.
Transforma a lista em uma estrutura de heap, onde o elemento máximo está sempre na raiz.
Repetidamente remove o elemento máximo da raiz e o coloca no final da lista, diminuindo o tamanho do heap.
Possui uma complexidade de tempo média e no pior caso de O(n log n) e é in-place (não requer memória adicional além da lista original).
Não é estável, ou seja, não necessariamente preserva a ordem relativa de elementos iguais.

In [26]:
def heapsort(arr):
    def heapify(arr, n, i):
        largest = i
        left = 2 * i + 1
        right = 2 * i + 2

        if left < n and arr[left] > arr[largest]:
            largest = left

        if right < n and arr[right] > arr[largest]:
            largest = right

        if largest != i:
            arr[i], arr[largest] = arr[largest], arr[i]
            heapify(arr, n, largest)

    n = len(arr)

    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)

    for i in range(n - 1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        heapify(arr, i, 0)

    return arr

In [27]:
df_rides = pd.read_csv('../input/bike-sharing-system-in-brasilia-brazil/df_rides.csv', sep=',')

In [28]:
df_rides.head(100)

,user_gender,user_birthdate,user_residence,ride_date,time_start,time_end,station_start,station_end,ride_duration,ride_late
0,M,1971-06-08,NaN,2018-01-01,06:05:18,06:21:33,11 - Rodoviária 2,41 - Instituto de Artes,16.250000,0.0
1,M,1989-02-11,DF,2018-01-01,06:27:01,06:32:17,26 - Ministério da Saude,28 - CNMP - Conselho Nacional do Ministério Pú...,5.266667,0.0
2,M,1968-07-19,NaN,2018-01-01,06:29:33,06:44:57,11 - Rodoviária 2,43 - Biblioteca Central,15.400000,0.0
3,M,1991-12-19,NaN,2018-01-01,06:53:53,06:59:45,10 - Ministério dos Transportes,6 - Rodoviária,5.866667,0.0
4,M,1969-03-03,DF,2018-01-01,06:58:56,17:40:04,15 - Brasil 21,11 - Rodoviária 2,641.133333,1.0
...,...,...,...,...,...,...,...,...,...,...
95,F,1969-01-29,DF,2018-01-01,13:33:30,14:11:24,38 - SQN 205,15 - Brasil 21,37.900000,0.0
96,F,1971-07-17,DF,2018-01-01,13:34:13,15:41:44,31 - EQS 204/205,31 - EQS 204/205,127.516667,1.0
97,M,1976-09-04,NaN,2018-01-01,13:37:42,15:34:30,15 - Brasil 21,15 - Brasil 21,116.800000,1.0
98,M,1974-06-26,PR,2018-01-01,13:40:13,14:20:15,35 - CLN 403,35 - CLN 403,40.033333,0.0
99,F,1981-03-19,DF,2018-01-01,13:41:24,14:20:50,35 - CLN 403,35 - CLN 403,39.433333,0.0

**Melhor Caso e Pior O(nLog(n):**

In [29]:
%%time


#Cópia dos 100 primeiros elementos do df_rides 
dfr = df_rides.head(100).copy()


#Cópia dos índices dos 100 primeiros elementos do df_rides
arr = df_rides.head(100).index.values.copy()

heapsort(arr)

CPU times: user 2.85 ms, sys: 0 ns, total: 2.85 ms
Wall time: 2.64 ms

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

**Pior Caso:**

Array desordenada

In [30]:
df_rides = df_rides.sample(frac=1,random_state=42)

In [31]:
df_rides.head(100)

,user_gender,user_birthdate,user_residence,ride_date,time_start,time_end,station_start,station_end,ride_duration,ride_late
145752,M,1950-08-25,DF,2018-05-27,18:01:12,18:12:16,4 - Torre de TV,12 - Rodoviária 3,11.066667,0.0
125244,M,1995-10-30,NaN,2018-05-13,14:58:13,16:58:33,15 - Brasil 21,15 - Brasil 21,120.333333,1.0
89296,NaN,1990-06-08,SP,2018-04-14,19:21:25,19:51:08,10 - Ministério dos Transportes,39 - CLN 406,29.716667,0.0
251533,F,1984-09-20,NaN,2018-08-08,17:16:55,17:21:19,22 - 102 Sul,21 - EQS 202 / 203,4.400000,0.0
278236,M,1963-03-02,DF,2018-08-26,13:32:56,14:15:20,25 - Deck Sul,25 - Deck Sul,42.400000,0.0
...,...,...,...,...,...,...,...,...,...,...
103237,F,1995-07-25,DF,2018-04-26,07:24:57,08:00:13,45 - Centro Olímpico,45 - Centro Olímpico,35.266667,0.0
118011,F,1992-03-18,NaN,2018-05-07,18:21:34,18:51:20,3 - Centro de Convenções,41 - Instituto de Artes,29.766667,0.0
35793,M,1996-12-17,DF,2018-02-17,06:50:26,06:54:38,6 - Rodoviária,8 - Ministério da Defesa,4.200000,0.0
130178,M,1995-10-17,NaN,2018-05-16,20:13:37,20:32:17,42 - PAT,38 - SQN 205,18.666667,0.0
134129,M,2004-09-07,NaN,2018-05-20,12:12:50,13:22:30,5 - Setor Hoteleiro Norte,5 - Setor Hoteleiro Norte,69.666667,1.0

In [32]:
%%time


#Cópia dos 100 primeiros elementos do df_rides 
dfr = df_rides.head(100).copy()


#Cópia dos índices dos 100 primeiros elementos do df_rides
arr = df_rides.head(100).index.values.copy()

heapsort(arr)

CPU times: user 1.81 ms, sys: 0 ns, total: 1.81 ms
Wall time: 1.78 ms

array([  1105,   2321,   5630,  12044,  16268,  18408,  18838,  19697,
        22786,  24669,  25857,  27021,  32936,  35793,  39945,  44836,
        46142,  51341,  51608,  53236,  54783,  63620,  76475,  76645,
        80641,  89296,  89665,  90036,  90796,  97152, 103237, 114238,
       118011, 119213, 120658, 125244, 127818, 129773, 130178, 131396,
       131452, 131535, 134129, 135971, 139104, 139321, 140265, 144389,
       144416, 145671, 145752, 147930, 151866, 163204, 165459, 165520,
       165548, 168238, 176174, 176567, 183711, 184639, 185411, 185793,
       187392, 192404, 192446, 194572, 201511, 203610, 206419, 214492,
       214826, 216357, 217499, 217828, 218408, 223783, 225094, 225120,
       226932, 227417, 228923, 234420, 242288, 245820, 246884, 247830,
       251533, 252731, 256552, 264020, 268057, 269642, 271166, 273516,
       277128, 278236, 282300, 286966])

### Quicksort

O Quicksort é um algoritmo de ordenação dividir para conquistar que escolhe um elemento pivô, reorganiza a lista de forma que os elementos menores que o pivô estejam à esquerda e os elementos maiores estejam à direita, e em seguida, ordena recursivamente as sublistas à esquerda e à direita do pivô.
Possui uma complexidade de tempo média de O(n log n) e um pior caso raro de O(n^2).
Pode ser bastante rápido na prática e é frequentemente usado como algoritmo de ordenação padrão em linguagens de programação como o Python (na função sorted() ou método list.sort()).
Sua escolha de pivô pode afetar seu desempenho; portanto, existem variações, como o Quicksort de Mediana de Três, para melhorar o desempenho em casos específicos.

In [33]:
def quick_sort(arr):
    if len(arr) <= 1:
        return arr

    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return quick_sort(left) + middle + quick_sort(right)

In [34]:
df_rides = pd.read_csv('../input/bike-sharing-system-in-brasilia-brazil/df_rides.csv', sep=',')

In [35]:
df_rides = df_rides.sample(frac=1,random_state=42)

In [36]:
df_rides.head(100)

,user_gender,user_birthdate,user_residence,ride_date,time_start,time_end,station_start,station_end,ride_duration,ride_late
145752,M,1950-08-25,DF,2018-05-27,18:01:12,18:12:16,4 - Torre de TV,12 - Rodoviária 3,11.066667,0.0
125244,M,1995-10-30,NaN,2018-05-13,14:58:13,16:58:33,15 - Brasil 21,15 - Brasil 21,120.333333,1.0
89296,NaN,1990-06-08,SP,2018-04-14,19:21:25,19:51:08,10 - Ministério dos Transportes,39 - CLN 406,29.716667,0.0
251533,F,1984-09-20,NaN,2018-08-08,17:16:55,17:21:19,22 - 102 Sul,21 - EQS 202 / 203,4.400000,0.0
278236,M,1963-03-02,DF,2018-08-26,13:32:56,14:15:20,25 - Deck Sul,25 - Deck Sul,42.400000,0.0
...,...,...,...,...,...,...,...,...,...,...
103237,F,1995-07-25,DF,2018-04-26,07:24:57,08:00:13,45 - Centro Olímpico,45 - Centro Olímpico,35.266667,0.0
118011,F,1992-03-18,NaN,2018-05-07,18:21:34,18:51:20,3 - Centro de Convenções,41 - Instituto de Artes,29.766667,0.0
35793,M,1996-12-17,DF,2018-02-17,06:50:26,06:54:38,6 - Rodoviária,8 - Ministério da Defesa,4.200000,0.0
130178,M,1995-10-17,NaN,2018-05-16,20:13:37,20:32:17,42 - PAT,38 - SQN 205,18.666667,0.0
134129,M,2004-09-07,NaN,2018-05-20,12:12:50,13:22:30,5 - Setor Hoteleiro Norte,5 - Setor Hoteleiro Norte,69.666667,1.0

**Melhor Caso O(nLog2(n):**

O vetor ta desordenado

In [37]:
%%time


#Cópia dos 100 primeiros elementos do df_rides 
dfr = df_rides.head(100).copy()


#Cópia dos índices dos 100 primeiros elementos do df_rides
arr = df_rides.head(100).index.values.copy()

quick_sort(arr)

CPU times: user 891 µs, sys: 0 ns, total: 891 µs
Wall time: 968 µs

[1105,
 2321,
 5630,
 12044,
 16268,
 18408,
 18838,
 19697,
 22786,
 24669,
 25857,
 27021,
 32936,
 35793,
 39945,
 44836,
 46142,
 51341,
 51608,
 53236,
 54783,
 63620,
 76475,
 76645,
 80641,
 89296,
 89665,
 90036,
 90796,
 97152,
 103237,
 114238,
 118011,
 119213,
 120658,
 125244,
 127818,
 129773,
 130178,
 131396,
 131452,
 131535,
 134129,
 135971,
 139104,
 139321,
 140265,
 144389,
 144416,
 145671,
 145752,
 147930,
 151866,
 163204,
 165459,
 165520,
 165548,
 168238,
 176174,
 176567,
 183711,
 184639,
 185411,
 185793,
 187392,
 192404,
 192446,
 194572,
 201511,
 203610,
 206419,
 214492,
 214826,
 216357,
 217499,
 217828,
 218408,
 223783,
 225094,
 225120,
 226932,
 227417,
 228923,
 234420,
 242288,
 245820,
 246884,
 247830,
 251533,
 252731,
 256552,
 264020,
 268057,
 269642,
 271166,
 273516,
 277128,
 278236,
 282300,
 286966]

**Pior Caso O(n²):**
O vetor esta ordenado

In [38]:
df_rides = pd.read_csv('../input/bike-sharing-system-in-brasilia-brazil/df_rides.csv', sep=',')

In [39]:
df_rides.head(100)

,user_gender,user_birthdate,user_residence,ride_date,time_start,time_end,station_start,station_end,ride_duration,ride_late
0,M,1971-06-08,NaN,2018-01-01,06:05:18,06:21:33,11 - Rodoviária 2,41 - Instituto de Artes,16.250000,0.0
1,M,1989-02-11,DF,2018-01-01,06:27:01,06:32:17,26 - Ministério da Saude,28 - CNMP - Conselho Nacional do Ministério Pú...,5.266667,0.0
2,M,1968-07-19,NaN,2018-01-01,06:29:33,06:44:57,11 - Rodoviária 2,43 - Biblioteca Central,15.400000,0.0
3,M,1991-12-19,NaN,2018-01-01,06:53:53,06:59:45,10 - Ministério dos Transportes,6 - Rodoviária,5.866667,0.0
4,M,1969-03-03,DF,2018-01-01,06:58:56,17:40:04,15 - Brasil 21,11 - Rodoviária 2,641.133333,1.0
...,...,...,...,...,...,...,...,...,...,...
95,F,1969-01-29,DF,2018-01-01,13:33:30,14:11:24,38 - SQN 205,15 - Brasil 21,37.900000,0.0
96,F,1971-07-17,DF,2018-01-01,13:34:13,15:41:44,31 - EQS 204/205,31 - EQS 204/205,127.516667,1.0
97,M,1976-09-04,NaN,2018-01-01,13:37:42,15:34:30,15 - Brasil 21,15 - Brasil 21,116.800000,1.0
98,M,1974-06-26,PR,2018-01-01,13:40:13,14:20:15,35 - CLN 403,35 - CLN 403,40.033333,0.0
99,F,1981-03-19,DF,2018-01-01,13:41:24,14:20:50,35 - CLN 403,35 - CLN 403,39.433333,0.0

In [40]:
%%time


#Cópia dos 100 primeiros elementos do df_rides 
dfr = df_rides.head(100).copy()


#Cópia dos índices dos 100 primeiros elementos do df_rides
arr = df_rides.head(100).index.values.copy()

quick_sort(arr)

CPU times: user 750 µs, sys: 0 ns, total: 750 µs
Wall time: 759 µs

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]